<div class="cart-header">
	 <div class="cart-sec simpleCart_shelfItem">
			<div class="cart-item cyc">
				 <img src="./public/images/l1.jpg" class="img-responsive" alt="">
			</div>
		   <div class="cart-item-info">
			<h3><a href="index.php?page=item&id=<?=$item->getId()?>"> <?=$item->getName()?> </a><span>Pickup time:</span></h3>
			<ul class="qty">
				<li><p>FREE delivery</p></li>
			</ul>
				 <div class="delivery">
				 <p>Prix : €<?=$item->getPrice()?></p>
				 <div class="clearfix"></div>
	        </div>	
		   </div>
		   <div class="clearfix"></div>
								
	  </div>
 </div>