<div class="cart-items">
	<div class="container">
	<div class="dreamcrub">
			   	 <ul class="breadcrumbs">
                    <li class="home">
                       <a href="index.php" title="Go to Home Page">Home</a>&nbsp;
                       <span>&gt;</span>
                    </li>
                    <li class="women">
                       Panier
                    </li>
                </ul>
                <ul class="previous">
                	<li><a href="index.php">Retour à la page précédente</a></li>
                </ul>
                <div class="clearfix"></div>
			   </div>
			 <h2>Mon panier</h2>
		<div class="cart-gd">
			 <?php require('apps/command_elem.php'); ?>
		
					   <div class="clearfix"></div>
					   <button class="achete">Valider le panier</button>
											
				  </div>
			  </div>
		</div>
	</div>
</div>