<div class="cart-header">
	 <div class="cart-sec simpleCart_shelfItem">
			<div class="cart-item cyc">
				<img src="<?=htmlentities($item->getPicture())?>" alt="images" class="img-responsive"/>
				
			</div>
		   <div class="cart-item-info">
			<h3><a href="index.php?page=item&id=<?=$item->getId()?>"> <?=$item->getName()?> </a><span>Pickup time:</span></h3>
			<ul class="qty">
				<li><p><?=$item->nbr?></p></li>
			</ul>
				 <div class="delivery">
				 <p>Prix : €<?=$item->getPrice()?></p>
				 <div class="clearfix"></div>
	        </div>	
		   </div>
		   <div class="clearfix"></div>
								
	  </div>
 </div>