<div class="cart-items">
	<div class="container">
	<div class="dreamcrub">
			   	 <ul class="breadcrumbs">
                    <li class="home">
                       <a href="index.html" title="Go to Home Page">Home</a>&nbsp;
                       <span>&gt;</span>
                    </li>
                    <li class="women">
                       Panier
                    </li>
                </ul>
                <ul class="previous">
                	<li><a href="index.html">Retour à la page précédente</a></li>
                </ul>
                <div class="clearfix"></div>
			   </div>
			 <h2>Mon panier</h2>
		<div class="cart-gd">
				<script>$(document).ready(function(c) {
					$('.close1').on('click', function(c){
						$('.cart-header').fadeOut('slow', function(c){
							$('.cart-header').remove();
						});
						});	  
					});
			   </script>
			 <div class="cart-header">
				 <div class="close1"> </div>
				 <div class="cart-sec simpleCart_shelfItem">
						<div class="cart-item cyc">
							 <img src="./public/images/l1.jpg" class="img-responsive" alt="">
						</div>
					   <div class="cart-item-info">
						<h3><a href="#"> Lorem Ipsum is not simply </a><span>Pickup time:</span></h3>
						<ul class="qty">
							<li><p>FREE delivery</p></li>
						</ul>
							 <div class="delivery">
							 <p>Frais d'envoi : $10.00</p>
							 <div class="clearfix"></div>
				        </div>	
					   </div>
					   <div class="clearfix"></div>
											
				  </div>
			 </div>
		
					   <div class="clearfix"></div>
											
				  </div>
			  </div>
		</div>
	</div>
</div>