<!-- <form method="POST">
	<input type="hidden" name="id_article" value="<?=$article->getId()?>">
	<div class="form-group">
		<label for="content">Content</label>
		<textarea class="form-control" id="content" name="content" placeholder="Content"></textarea>
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
</form> -->

<div class="reviews-tabs">
      <!-- Main component for a primary marketing message or call to action -->
      <ul class="nav nav-tabs" id="myTab">
        <li class="test-class"><a class="deco-none" href="#source">Reviews (7)</a></li>
      </ul>

		<div class="media response-info">
							<div class="media-left response-text-left">
								<a href="#">
									<img class="media-object" src="images/icon1.png" alt="" />
								</a>
								<h5><a href="#">Username</a></h5>
							</div>
							<div class="media-body response-text-right">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,There are many variations of passages of Lorem Ipsum available, 
									sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								<ul>
									<li>JAN 28, 2015</li>
									<li><a href="single.html">Reply</a></li>
								</ul>		
							</div>
							<div class="clearfix"> </div>
   </div>
			
