<form method="POST">
	<input type="hidden" name="id_item" value="<?=$item->getId()?>">
	<div class="reviews-tabs">
		<div class="form-group">
			<label for="content">Commentaire</label>
			<textarea class="form-control" name="content"></textarea>
		</div>
	</div>
	<div class="rating">
			<a href="#5" title="Donner 5 étoiles" data-rate="5">☆</a><!--
	   	--><a href="#4" title="Donner 4 étoiles" data-rate="4">☆</a><!--
	   	--><a href="#3" title="Donner 3 étoiles" data-rate="3">☆</a><!--
	   	--><a href="#2" title="Donner 2 étoiles" data-rate="2">☆</a><!--
		--><a href="#1" title="Donner 1 étoile" data-rate="1">☆</a>
	</div>
	<br>
	<input type="hidden" name="rate" value="" id="rate">
	<div class="clearfix"> </div>
	<button type="submit" class="btn btn-default">Submit</button>
</form>
<script>
	$('.rating>a').click(function()
{
	var rate = $(this).data('rate');
	$('#rate').val(rate);
});
</script>
