 
<div class="registration-grids">
			<div class="reg-form">
				<div class="reg">
				
 					<form method="post">
						<input type="hidden" name="action" value="create_category">

 						<ul>
							 <li class="text-info">Nom de la catégorie: </li>
							 <li><input type="text" name="name" id="name" ></li>
						 </ul>
						 <ul>
							 <li class="text-info">Description: </li>
							 <textarea  class="form-control" id="description" name="description" placeholder="description"></textarea>
						 </ul>

						 </ul>						
						 <button type="submit" >Submit</button>
					 </form>
				</div>
			</div>
		</div>			






