 
<div class="registration-grids">
			<div class="reg-form">
				<div class="reg">

 					<form method="post">
						 <ul>
							 <li class="text-info">Nom de l'article: </li>
							 <li><input type="text" name="name" id="name" ></li>
						 </ul>
						 <ul>
							 <li class="text-info">Catégorie: </li>
							 <li><select name="id_category">
									  
								<?php for ($count = 0; $count < count($list); $count++) : ?>
									  <option value="<?=$list[$count]->getId()?>"><?=$list[$count]->getName()?></option>
								<?php endfor; ?>
								

								</select></li>
						 </ul>
						 <ul>
							 <li class="text-info">Stock: </li>
							 <li><input type="number" name="stock" id="stock" ></li>
						 </ul>
						 <ul>
							 <li class="text-info">Prix: </li>
							 <li><input type="number" name="price" id="price" ></li>
						 </ul>

						 <ul>
							 <li class="text-info">Description: </li>
							 <textarea  class="form-control" id="description" name="description" placeholder="description"></textarea>
						 </ul>

		



						 </ul>						
						 <button type="submit" >Submit</button>
					 </form>
				</div>
			</div>
		</div>			






