<h1>Create Article</h1>
<form method="POST">
	<div class="form-group">
		<label for="title">Title</label>
		<input type="text" class="form-control" id="title" name="title" placeholder="Title">
	</div>
	<div class="form-group">
		<label for="content">Content</label>
		<textarea class="form-control" id="content" name="content" placeholder="Content"></textarea>
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
</form>