 
<div class="registration-grids">
			<div class="reg-form">
				<div class="reg">
 					<form method="post">
						<input type="hidden" name="action" value="create_item">
						<ul>
							 <li class="text-info">Nom de l'article: </li>
							 <li><input type="text" name="name" id="name" ></li>
						</ul>
						<ul>
							 <li class="text-info">Catégorie: </li>
							 <li><select name="id_category">
									  
								<?php for ($count = 0; $count < count($list); $count++) : ?>
									  <option value="<?=$list[$count]->getId()?>"><?=$list[$count]->getName()?></option>
								<?php endfor; ?>
								

								</select></li>
						</ul>
						  
						<ul>
							 <li class="text-info">Choix de la couleur: </li>
							 <li>
								  <select name="color" id="color">
								 	<option value="Blanc">Blanc</option>
								 	<option value="Rouge">Rouge</option>
								 	<option value="Bleu">Bleu</option>
								 	<option value="Noir">Noir</option>
								 </select>
							 </li>
						 </ul>
						 
						<ul>
							 <li class="text-info">Stock: </li>
							 <li><input type="number" name="stock" id="stock" ></li>
						</ul>
						 
						<ul>
							 <li class="text-info">Prix: </li>
							 <li><input type="number" name="price" id="price" ></li>
						</ul>

						<ul>
							 <li class="text-info">Description: </li>
							 <li>
								 <textarea name="description" id="description" cols="30" rows="10"></textarea>
							 </li>
							 
						</ul>


						<div>
					        <label for="image">Lien de l'image :</label>
					        <input type="text" id="image" name="picture" /> 
					    </div>

						<ul>
							 <li class="text-info">Taille disponilbe: </li>
							 <li>
								 <select name="size" id="size">
								 	<option value="XS">XS</option>
								 	<option value="S">S</option>
								 	<option value="M">M</option>
								 	<option value="L">L</option>
								 </select>
							 </li>
						</ul>
						 <button type="submit" >Submit</button>
					 </form>
				</div>
			</div>
		</div>			






