<div class="news-letter">
			<div class="container">
				<div class="join">
					<h6>Newsletter</h6>
					<div class="sub-left-right">
						<form>
							<input type="text" value="E-mail" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your Email Here';}" />
							<input type="submit" value="je m'abonne" />
						</form>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
		</div>
		<div class="footer">
		<div class="container">
		 <div class="footer_top">
			<div class="span_of_4">
				<div class="col-md-4 span1_of_4">
					<h4>Boutique</h4>
					<ul class="f_nav">
						<li><a href="#">nouvelle collection</a></li>
						<li><a href="#">T-shirts</a></li>
						<li><a href="#">Pull</a></li>
						<li><a href="#">Chaussettes</a></li>
						<li><a href="#">Accesoires</a></li>
					</ul>	
				</div>
				<div class="col-md-4 span1_of_4">
					<h4>Aide</h4>
					<ul class="f_nav">
						<li><a href="#">Questions</a></li>
						<li><a href="#">FAQ</a></li>
						<li><a href="#">Conditions d'utilisations</a></li>
					</ul>	
				</div>
				<div class="col-md-4 span1_of_4">
					<h4>Compte</h4>
					<ul class="f_nav">
						<li><a href="account.html">Se connecter</a></li>
						<li><a href="register.html">Créer un compte</a></li>
						<li><a href="checkout.html">Votre panier</a></li>
					</ul>				
				</div>
				<div class="clearfix"></div>
				</div>
		  </div>
		  
		  <div class="copyright text-center">
				<p>© 2017 Chihuaworld</p>
		  </div>
		</div>
		</div>