<!-- header-section-starts -->
	<div class="header">
		<div class="header-top-strip">
			<div class="container">
				<div class="header-top-left">
					<ul>
						<li><a href="index.php?page=login"><span class="glyphicon glyphicon-user"> </span>Login</a></li>
						<li><a href="index.php?page=register"><span class="glyphicon glyphicon-lock"> </span>Créer un compte</a></li>			
					</ul>
				</div>
				<div class="header-right">
						<div class="cart box_1">
							<a href="index.php?page=command">
							</a>	
							<div class="clearfix"> </div>
						</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- header-section-ends -->
			<div class="banner-top">
		<div class="container">
				<nav class="navbar navbar-default" role="navigation">
	    <div class="navbar-header">
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
	        </button>
				<div class="logo">
					<h1><a href="index.php"><span><img src="./public/images/patte.svg" width="30px" alt=""></span> Chihuaworld</a></h1>
				</div>
	    </div>
	    <!--/.navbar-header-->
	
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	        <ul class="nav navbar-nav">
					<li><a href="index.php">Accueil</a></li>
		        	<?php foreach ($list AS $category) : ?>
						<li><a href="index.php?page=id_category=<?=$category->getId()?>"><?=$category->getName()?></a></li>
					<?php endforeach; ?>
	        </ul>
	    </div>
	    <!--/.navbar-collapse-->
	</nav>