<h1><?=htmlentities($item->getName())?></h1>
<p><?=htmlentities($item->getDescription())?></p>
<div>
	<div class="pull-right">
		<span class="label label-info"><?=htmlentities($item->getAuthor()->getLogin())?></span>
		<!--<span class="label label-default">alice</span>
		<span class="label label-primary">story</span>
		<span class="label label-success">blog</span>
		<span class="label label-warning">Warning</span>
		<span class="label label-danger">Danger</span>-->
	</div>         
</div>
<br/>
<fieldset>
	<legend>Commentaires</legend>
	<?php require('apps/create_review.php'); ?>
	<div class="block_comments">
		<?php require('apps/reviews.php'); ?>
	</div>
</fieldset>

