<div class="col-md-4 product simpleCart_shelfItem text-center">
	<a href="single.html"><img src="public/images/p1.jpg" alt="" /></a>
	<div class="mask">
		<a href="index.php?page=item&id=1">Quick View</a>
	</div>
	<a class="product_name" href="index.php?page=item&id=1"><?=htmlentities($item->getName())?></a>
	<p><a class="item_add" href="#"><i></i> <span class="item_price"><?=htmlentities($item->getPrice())?></span></a></p>
</div>
<div class="clearfix"></div>
					