
<div class="container">
	<div class="products-page">
		<div class="products">
			<div class="product-listy">
				<h2>Nos produits</h2>
				<ul class="product-list">
					<?php foreach ($list AS $category) : ?>
						<li><a href="index.php?page=id_category=<?=$category->getId()?>"><?=$category->getName()?></a></li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
		<div class="new-product">
			<form method="post">
				<input type="hidden" name="id_item" value="<?=$item->getId()?>">
			<div class="col-md-5 zoom-grid">
				<div class="thumb-image"> 
					<img src="./public/images/<?=htmlentities($item->getId())?>.jpg" data-imagezoom="true" class="img-responsive" alt="" />
				</div>
						
			</div>
			<div class="col-md-7 dress-info">
				<div class="dress-name">
					<h3><?=htmlentities($item->getName())?></h3>
					<span><?=htmlentities($item->getPrice())?> €</span>
					<div class="clearfix"></div>
					<p><?=htmlentities($item->getDescription())?></p>
				</div>
				<div class="span span2">
					<p class="left">STOCK</p>
					<p class="right"><input type="number" min="1" name="quantity" value="1">/<?=$item->getStock()?></p>
					<div class="clearfix"></div>
				</div>
				<div class="span span3">
					<p class="left">COULEUR</p>
					<p class="right">
						<select class="domains valid" name="color">
							<?php foreach($item->getColor() AS $color) : ?>
						   		<option style="background-color:<?=$color?>;color:white"><?=$color?></option>
							<?php endforeach; ?>
					   </select>
					</p>
					<div class="clearfix"></div>
				</div>
				<div class="span span4">
					<p class="left">TAILLE</p>
					<p class="right"><span class="selection-box">
						<select class="domains valid" name="size">
							<?php foreach($item->getSize() AS $size) : ?>
						   		<option><?=$size?></option>
							<?php endforeach; ?>
					   </select>
								</span></p>
					<div class="clearfix"></div>
				</div>
					<div class="purchase">
							<input type="submit" value="Acheter">

						<div class="social-icons">
							<ul>
								<li><a class="facebook1" href="#"></a></li>
								<li><a class="twitter1" href="#"></a></li>
								<li><a class="googleplus1" href="#"></a></li>
							</ul>
						</div>
						<div class="clearfix"></div>
					</div>
				</form>
					<script src="./public/js/imagezoom.js"></script>
					<!-- FlexSlider -->
					<script defer src="./public/js/jquery.flexslider.js"></script>
					<script>
						// Can also be used with $(document).ready()
						$(window).load(function() {
						  $('.flexslider').flexslider({
							animation: "slide",
							controlNav: "thumbnails"
						  });
						});
					</script>
				</div>
				<div class="clearfix">
				</div>
				<div class="reviews-tabs">
      <!-- Main component for a primary marketing message or call to action --> 
      				<ul class="nav nav-tabs">
              			<li class="test-class">
              				<a class="deco-none" href="#source">Avis des acheteurs</a>
              			</li>
      				</ul>
	    			<div>
	       				<?php require('apps/reviews.php'); ?>
	       				<?php require('apps/create_review.php'); ?>
					</div>
        
        		</div>
      		</div>		
		</div>
	</div>
		<div class="clearfix"></div>
</div>



	






