<div class="container">
			<div class="main-content">
				<div class="online-strip">
					
				<div class="products-grid">
				<header>
					<h3 class="head text-center">Nos produits</h3>
				</header>
				
				<?php require ('apps/item_elem.php'); ?> 

				</div>

				<br>
				<div class="clearfix"></div>
			</div>

		</div>
<div>







<!-- <div class="containerArticles">
	<h1>Les Articles</h1>
	<?php //require('apps/articles_elem.php'); ?>
</div> -->