<form method="post">
<input type="hidden" name="action" value="login">
<div class="content">
	<div class="container">
		<div class="login-page">
			    <div class="dreamcrub">
			   	 <ul class="breadcrumbs">
                    <li class="home">
                       <a href="index.html" title="Go to Home Page">Home</a>&nbsp;
                       <span>&gt;</span>
                    </li>
                    <li class="women">
                       Login
                    </li>
                </ul>
                <ul class="previous">
                	<li><a href="index.html">Page précédente</a></li>
                </ul>
                <div class="clearfix"></div>
			   </div>
			   <div class="account_grid">
			   <div class="col-md-6 login-left wow fadeInLeft" data-wow-delay="0.4s">
			  	 <h2>NEW CUSTOMERS</h2>
				 <p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
				 <a class="acount-btn" href="register.html">Create an Account</a>
			   </div>
			   <div class="col-md-6 login-right wow fadeInRight" data-wow-delay="0.4s">
			  	<h3>REGISTERED CUSTOMERS</h3>
				<p>If you have an account with us, please log in.</p>
				<form>
				  <div>
					<span>Pseudo ou mail<label>*</label></span>
					<input name="login" type="text"> 
				  </div>
				  <div>
					<span>Mot de passe<label>*</label></span>
					<input name="password" type="password"> 
				  </div>
				  <a class="forgot" href="#">Mot de passe oublié</a>
				  <input type="submit" value="Se connecter">
			    </form>
			   </div>	
			   <div class="clearfix"> </div>
			 </div>
		   </div>
</div>
</form>














<!-- 
ANCIEN MVC  -->
<!-- <h1>Login</h1>
<form method="POST">
	<input type="hidden" name="action" value="login">
	<div class="form-group">
		<label for="login">Login</label>
		<input type="text" class="form-control" id="login" name="login" placeholder="Login">
	</div>
	<div class="form-group">
		<label for="password">Password</label>
		<input type="password" class="form-control" id="password" name="password" placeholder="Password">
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
</form> -->