<form class="registration-form" method="post">
	<input type="hidden" name="action" value="register">
	<div class="container">
	<div class="dreamcrub">
			   	 <ul class="breadcrumbs">
                    <li class="home">
                       <a href="index.php" title="Go to Home Page">Home</a>&nbsp;
                       <span>&gt;</span>
                    </li>
                    <li class="women">
                       s'enregistrer
                    </li>
                </ul>
                <ul class="previous">
                	<li><a href="index.php">page précédente</a></li>
                </ul>
                <div class="clearfix"></div>
			   </div>
		<h2>S'inscrire</h2>
		<div class="registration-grids">
			<div class="reg-form">
				<div class="reg">
					 <p>Bienvenue sur Chiuhaworld !</p>
					 <p>Si vous êtes déjà inscrits <a href="index.php?page=login">cliquez ici.</a></p>
					 <form>
					 	 <ul>
							 <li class="text-info">Pseudo: </li>
							 <li><input type="text" name="login"></li>
						 </ul>
						 <ul>
							 <li class="text-info">Prénom: </li>
							 <li><input type="text" name="firstname"></li>
						 </ul>
						 <ul>
							 <li class="text-info">Nom: </li>
							 <li><input type="text" name="lastname"></li>
						 </ul>				 
						<ul>
							 <li class="text-info">Email: </li>
							 <li><input type="text" name="email"></li>
						 </ul>
						 <ul>
							 <li class="text-info">Date de naissance: </li>
							 <li><input type="date" name="birthdate"></li>
						 </ul>
						 <ul>
							 <li class="text-info">Mot de passe: </li>
							 <li><input type="password" name="password1"></li>
						 </ul>
						 <ul>
							 <li class="text-info">Répétez le mot de passe:</li>
							 <li><input type="password" name="password2"></li>
						 </ul>
						 <ul>
							 <li class="text-info">Adresse:</li>
							 <li><input type="text" name="adress"></li>
						 </ul>						
						 <input type="submit" name="register">
						 <p class="click">Lire le règlement général.<a href="#">J'accepte les conditions.</a></p> 
					 </form>
				 </div>
			</div>
			<div class="reg-right">
				 <h3>Completely Free Account</h3>
				 <div class="strip"></div>
				 <p>Pellentesque neque leo, dictum sit amet accumsan non, dignissim ac mauris. Mauris rhoncus, lectus tincidunt tempus aliquam, odio 
				 libero tincidunt metus, sed euismod elit enim ut mi. Nulla porttitor et dolor sed condimentum. Praesent porttitor lorem dui, in pulvinar enim rhoncus vitae. Curabitur tincidunt, turpis ac lobortis hendrerit, ex elit vestibulum est, at faucibus erat ligula non neque.</p>
				 <h3 class="lorem">Lorem ipsum dolor.</h3>
				 <div class="strip"></div>
				 <p>Tincidunt metus, sed euismod elit enim ut mi. Nulla porttitor et dolor sed condimentum. Praesent porttitor lorem dui, in pulvinar enim rhoncus vitae. Curabitur tincidunt, turpis ac lobortis hendrerit, ex elit vestibulum est, at faucibus erat ligula non neque.</p>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</form>