<div class="row">
	<div class="col-sm-2">
		<div class="thumbnail">
			<img class="img-responsive user-photo" src="https://s-media-cache-ak0.pinimg.com/736x/75/5b/2a/755b2a90e7f028e956de61827e544ff8.jpg">
		</div>
	</div>
	<div class="col-sm-10">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong><?=htmlentities($review->getCustomer()->getLogin())?></strong> 
				<?php
					$i = 1;
					while($i <= 5)
					{
						if($i <= intval($review->getRate()))
							echo '<span style="color:red">☆</span>';
							
					
					else
					

								echo "<span>☆</span>";
							$i++;
					}
					?>
				<span class="text-muted"><?=htmlentities($review->getDate())?></span>
			</div>
			<div class="panel-body">
				<?=htmlentities($review->getContent())?>
			</div>
		</div>
	</div>
</div>

